name:                geeklets-hs
version:             0.1.0.0
github:              "tbidne/geeklets-hs"
license:             BSD3
author:              "Thomas Bidne"
maintainer:          "tbidne@gmail.com"
copyright:           "2019 Thomas Bidne"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tbidne/geeklets-hs#readme>

dependencies:
- base >= 4.7 && < 5
- process
- regex-tdfa

ghc-options:
  - -O2
  - -Wall
  - -Wpartial-fields
  - -Wmissing-home-modules
  - -Widentities
  - -Wmissing-export-lists
  - -Wcompat
  - -Wredundant-constraints
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns

library:
  source-dirs: src

executables:
  geeklets-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geeklets-hs
